Add SSM Distributor
aws-ia/cfn-abi-crowdstrike-fcs pull request #40
Opened 2023-11-14 18:14 UTC by ryanjpayne

Add stacksets to deploy SSM Associations in each region/account to automatically install the Falcon sensor on Windows and Linux instances.

2023-11-15 19:17 UTC, ryanjpayne commented
@kkvinjam

2023-12-06 00:16 UTC, kkvinjam commented
/do-e2e-tests

2023-12-06 02:12 UTC, kkvinjam requested changes

2023-12-06 02:12 UTC, kkvinjam commented on templates/crowdstrike_init_stack.yaml
> +      BucketName: !Sub ${SourceS3BucketNamePrefix}-${AWS::StackName}
Using `AWS::StackName` results in S3 bucket creation to fail, when there are captial letters in the stackname. This is not scalable, please reset to `${AWS::AccountId}-${AWS::Region}`

2023-12-08 18:45 UTC, kkvinjam commented
/do-e2e-tests

2023-12-08 21:37 UTC, kkvinjam approved these changes

2023-12-08 22:37 UTC, kkvinjam requested changes
There are few additional issues reported by the scanner. Chimed you the details, please review and fix them. Thanks

2023-12-12 18:36 UTC, kkvinjam requested changes
In addition to the commented changes. Additional review and rule_supress needed at File: /templates/crowdstrike_init_stack.yaml:854-860

2023-12-12 18:36 UTC, kkvinjam commented on templates/aws_cspm_cloudformation_v2.json
> +        "cfn_nag": {
Incorrect suppression. Example below. For additional information, refer to [the doc](https://www.checkov.io/2.Basics/Suppressing%20and%20Skipping%20Policies.html).

```
  MyDB:
    Metadata:
      checkov:
        skip:
          - id: "CKV_AWS_157"
            comment: "Ensure that RDS instances have Multi-AZ enabled"
    Type: "AWS::RDS::DBInstance"
    Properties:
```

2023-12-12 18:36 UTC, kkvinjam commented on templates/aws_cspm_cloudformation_v2.json
> +              "id": "CKV_AWS_116",
Same as above. Incorrect suppression. Please fix.

2023-12-18 22:56 UTC, kkvinjam commented
/do-e2e-tests

2023-12-19 02:59 UTC, kkvinjam approved these changes

2023-12-19 02:59 UTC, merged