add secret for sensor management api credentials
aws-ia/cfn-abi-crowdstrike-fcs pull request #47
Opened 2024-01-23 15:15 UTC by ryanjpayne

- Update crowdstrike_init_stack.yaml with parameter to select storage method for API credentials used by Sensor Management
- Update aws_cspm_cloudformation_v2.json with parameter and resources to store API credentials used by Sensor Management in a secret
- Update documentation for new parameter

2024-01-23 15:32 UTC, kkvinjam requested changes
Could you please add a test case in `.taskcat.yml` to test this new option.

2024-01-23 15:37 UTC, ryanjpayne commented
> Could you please add a test case in `.taskcat.yml` to test this new option.

Added test case cw-test-smlambda
Test case will store API credentials in lambda env vars
Default test case will use the secret option

2024-01-23 15:53 UTC, kkvinjam commented
> > Could you please add a test case in `.taskcat.yml` to test this new option.
> 
> Added test case cw-test-smlambda Test case will store API credentials in lambda env vars Default test case will use the secret option

Please add run_test "cw-test-smlambda"  to below file.

https://github.com/aws-ia/cfn-abi-crowdstrike-fcs/blob/035e5baf8eb5e8412bcc08d2e1d081c03160aad9/.project_automation/functional_tests/entrypoint.sh#L49

2024-01-23 16:03 UTC, ryanjpayne commented
> > Could you please add a test case in `.taskcat.yml` to test this new option.
> 
> Added test case cw-test-smlambda Test case will store API credentials in lambda env vars Default test case will use the secret option

ack

2024-01-24 18:37 UTC, kkvinjam requested changes
Please check below failure, which is deviating from best practices.

```Check: CKV_AWS_149: "Ensure that Secrets Manager secret is encrypted using KMS CMK"
	FAILED for resource: AWS::SecretsManager::Secret.CrowdStrikeSensorManagementFalconCredentialsSecret
	File: /templates/aws_cspm_cloudformation_v2.json:452-460
	Guide: https://docs.prismacloud.io/en/enterprise-edition/policy-reference/aws-policies/aws-general-policies/ensure-that-secrets-manager-secret-is-encrypted-using-kms

		452 |     "CrowdStrikeSensorManagementFalconCredentialsSecret": {
		453 |       "Type": "AWS::SecretsManager::Secret",
		454 |       "Condition": "ShouldCreateSensorManagementCredentialsSecret",
		455 |       "Properties": {
		456 |         "Name": "/CrowdStrike/CSPM/SensorManagement/FalconAPICredentials",
		457 |         "Description": "Falcon API credentials. Used by the 1-Click sensor management orchestrator.",
		458 |         "SecretString": {"Fn::Sub": "{\"ClientId\":\"${ClientID}\",\"ClientSecret\":\"${ClientSecret}\"}"}
		459 |       }
		460 |     },

2024-01-24 20:06 UTC, kkvinjam commented
/do-e2e-tests

2024-01-24 23:51 UTC, kkvinjam approved these changes

2024-01-24 23:51 UTC, merged