DSPM
aws-ia/cfn-abi-crowdstrike-fcs pull request #73
Opened 2024-12-03 19:23 UTC by ryanjpayne

### CrowdStrike DSPM

#### Complete data discovery in seconds
Instantly catalog all databases, managed and unmanaged as well as used and unused.

#### Continuous data security posture & risk management
Continuous monitoring of data risks, including sensitive data exposure, mishandling, unauthorized access, and networking issues.

#### Proactive data loss prevention 
Continuous data flow monitoring defends sensitive data against loss, theft, misuse, and unauthorized access.

### Changes
- Add dspm.yml stack for provisioning each account
- Add aws_cspm_cloudformation_dspm_env.yml for provisioning regional resources
- Add stackset reference to init stack

2024-12-10 15:44 UTC, ryanjpayne commented
We can hold off on this PR for now, waiting on product documentation and update to the lambda runtime

2025-01-22 19:45 UTC, ryanjpayne commented
We can test this now

2025-01-22 20:24 UTC, kkvinjam commented
@ryanjpayne please do not update `.project_config.yml`. Only VERSION file need to be updated.

2025-01-25 03:33 UTC, kkvinjam commented
/do-e2e-tests

2025-01-29 04:14 UTC, kkvinjam requested changes

2025-01-29 04:14 UTC, kkvinjam commented on templates/dspm-stack.yml
> +            comment: False Positive, no secret
Please add Ref https://github.com/bridgecrewio/checkov/issues/5282 to the comment.

2025-06-05 20:10 UTC, closed without merging